# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-13 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='emergency_contact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact_for', to='tests.Cat'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='siblings',
            field=models.ManyToManyField(related_name='related_to', to='tests.Cat'),
        ),
    ]
